# Use Docker environment
sudo: false

# Setup build matrix
language: php
php:
  - 5.5
  - 5.6
  - 7

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

services:
  - mongodb
  - mysql

addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server

# Dependencies
before_install:
  - pecl install mongodb
  - composer self-update

install:
  - travis_retry composer update --no-interaction --prefer-source --dev $PREFER_LOWEST

script: composer test
